### PR TITLE
Add Alias Method to Segment.io

### PR DESCRIPTION
**Pull request by leore**
Segment.io needs alias method to merge anonymous users with registered users ager sign up.

### CODE REVIEW

**Comment by leore** [comment]
@luisfarzati can I get this merged?

**Comment by shrav** [comment]
+1

**Comment by leore** [comment]
@luisfarzati are you waiting on any additional information?

**Comment by leore** [comment]
@lunks can this please get merged :)

**Comment by lunks** [comment]
I will merge this over the weekend, probably. :)

**Pull request merged**
