### PR TITLE
Assigned the default event category "Event", as it's required by Google

### PR DESCRIPTION
**Pull request by trolleycrash**
Per the discussion in https://github.com/luisfarzati/angulartics/issues/81, I've added a default event category of "Event" to prevent events getting dropped without warning.

### CODE REVIEW

**Comment by lunks** [comment]
I think we can remove the comment given the code is pretty straightforward.

**Comment by trolleycrash** [comment]
I agree the code is quite clear, but **why** the code is there is considerably less clear. I'll clarify the comment, though.

**Comment by trolleycrash** [comment]
Let me know if you still this I should just axe the comment completely.

**Comment by lunks** [comment]
This one definitely looks better. I don't like the comment much because this is related to Google API which people should read before using something like angulartics, but I guess it doesn't hurt to leave it there. Could you rebase, please?

**Comment by trolleycrash** [comment]
Done and done.

**Comment by lunks** [comment]
Thank you!

**Pull request merged**
