### PR TITLE
Fix for issue 271 - events do not send 'page' to google analytics.

### PR DESCRIPTION
**Pull request by ormagomy**
This PR fixes issue #271 by sending the 'page' property along with google analytics calls. Callers can specify their own properties.page value, otherwise it is pulled from window.location.hash.  The '#' is removed from the beginning of the hash.  I would have preferred to use angular's $location service to get $location.url(), which is a better solution, which includes the search params.  However, I was not able to find a way to do this, since the callback function is registered inside of a module.config block.

### CODE REVIEW

**Comment by johanlunds** [comment]
We also want this.

**Comment by russelltaylor05** [comment]
We need this as well!

**Comment by lunks** [comment]
Could you please rebase?

**Comment by ormagomy** [comment]
Rebase done.

**Pull request merged**
