### PR TITLE
Added additionalAccountNames config option for ga.js tracking code.

### PR DESCRIPTION
**Pull request by Ignigena**
Using Angulartics on a site which is still using the ga.js tracking code. This site has multiple account names which needed tracking so this adds the additionalAccountNames configuration option for ga.js in addition to analytics.js which was already implemented.

### CODE REVIEW

**Comment by lunks** [comment]
Could you please rebase?

**Comment by Ignigena** [comment]
Absolutely! Done.

**Comment by lunks** [comment]
Could you please rebase again? Sorry about that. :sweat_smile:

**Comment by Ignigena** [comment]
Done again! No worries :)

**Pull request merged**
