### PR TITLE
Updated readme documentation for v2

### PR DESCRIPTION
**Pull request by DanWilkerson**
Added documentation for implementation with the GTM v2 interface.

### CODE REVIEW

**Comment by stramel** [comment]
Great job! :clap:

**Comment by lunks** [comment]
Could someone else please give it a try? It seems there's a lot to do and I'd like to know beforehand from other people this indeed works.

**Comment by DanWilkerson** [comment]
Just a heads-up, starting June 1st all containers will be forced to switch to the v2 interface. v1 migrations will work fine as-is, thanks to some handy engineering on Google's part, but anyone starting fresh will need to use the v2 configuration.

**Comment by stramel** [comment]
@DanWilkerson Should the documentation have User tracking documented as well? Perhaps a separate documentation page for common GTM v2 questions?

**Comment by DanWilkerson** [comment]
I can add something if there's interest.

**Comment by luisfarzati** [comment]
Sorry, I saw this after #382. Feel free to resubmit with adjustments if there's anything missing there. Thank you!

**Comment by DanWilkerson** [comment]
@luisfarzati #382 is okay, but there is some language I would clean up. I will resubmit.

**Comment by DanWilkerson** [comment]
@luisfarzati On a second look, everything is kosher. Thanks for updating!

**Pull request closed without merging**
